apiVersion: v1
kind: Secret
metadata:
  name: pastebincollector-secrets
type: Opaque
stringData:
    # path in the pod (from the yaml file) to the year/month/day format directory tree of pastes
    PASTEBIN_PATH: /paste
    # path in the pod (from the yaml file) to the year/month/day format directory tree of extracted malware
    MALWARE_PATH: /malware
    # *relative* path in the *analyzer* *pod* to the extracted malware. Must be relative...if this
    # starts with a / , python's os.path.join will discard everything to the left of it.
    ANALYZER_PATH: pastebin-extractions
    # url to analyzer
    ANALYZER_URL: http://malware-analysis-site:8000/api/job
    # API token to use to submit jobs to the analyzer
    ANALYZER_TOKEN: ""
    # password to use to encrypt zip archives (not supported by python at the moment
    # ...left in because I'm overly optimistic.
    ARCHIVE_PASSWORD: infected
