apiVersion: v1
kind: Secret
metadata:
  name: pastebincollector-secrets
type: Opaque
stringData:
    PASTEBIN_PATH: /paste
    MALWARE_PATH: /malware
    ARCHIVE_PATH: /RAID
    ARCHIVE_URL: http://malware-analysis-site:8000/api/job
    ARCHIVE_TOKEN: ""
    ARCHIVE_PASSWORD: infected
