apiVersion: v1
kind: Secret
metadata:
  name: pastebincollector-secrets
type: Opaque
stringData:
    # path in the pod (from the yaml file) to the year/month/day format directory tree of pastes
    PASTEBIN_PATH: /paste
    # path in the pod (from the yaml file) to the year/month/day format directory tree of extracted malware
    MALWARE_PATH: /malware
    # path in the *archiver* *pod* to the extracted malware
    ANALYZER_PATH: /RAID/pastebin-extractions
    # url to analyzer
    ANALYZER_URL: http://malware-analysis-site:8000/api/job
    # API token to use to submit jobs to the analyzer
    ANALYZER_TOKEN: ""
    # password to use to encrypt zip archives (not supported by python at the moment
    # ...left in because I'm overly optimistic.
    ARCHIVE_PASSWORD: infected
