apiVersion: v1
kind: Secret
metadata:
  name: pastebincollector-secrets
type: Opaque
stringData:
    # path in the pod (from the yaml file) to the year/month/day format directory tree of pastes
    PASTEBIN_PATH: /paste
    # path in the pod (from the yaml file) to the year/month/day format directory tree of extracted malware
    MALWARE_PATH: /malware
    # path in the *archiver* *pod* to the extracted malware
    ANALYZER_PATH: /RAID/pastebin-extractions
    # u
    ANALYZER_URL: http://malware-analysis-site:8000/api/job
    ANALYZER_TOKEN: ""
    ARCHIVE_PASSWORD: infected
