apiVersion: v1
kind: PersistentVolume
metadata:
  name: pastebin-pv
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pastebin
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: pastebin-pv
    volumeAttributes:
      source: "//192.168.1.197/pastebin"
    nodeStageSecretRef:
      name: pastebin-smb-secrets
      namespace: pastebin
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pastebin-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: pastebin-pv
  storageClassName: pastebin
